spring:
  application:
    name: ipl-dashboard
  datasource:
    url: jdbc:mysql://localhost:3306/ipl_db?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
